version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: faith-matrimony-db
    environment:
      POSTGRES_DB: faith_matrimony
      POSTGRES_USER: matrimony_user
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: